---
name: SUPER
version: 1.12
author:
  - 'Created by Simon Cozens, C<simon@cpan.org>.'
abstract: control superclass method dispatch
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: ''
build_requires:
  Test::Simple: 0.61
provides:
  DB:
    file: lib/SUPER.pm
  SUPER:
    file: lib/SUPER.pm
    version: 1.12
  UNIVERSAL:
    file: lib/SUPER.pm
generated_by: Module::Build version 0.2709
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
