---
abstract: 'control superclass method dispatch'
author:
  - chromatic
build_requires:
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SUPER
requires:
  Carp: '0'
  Exporter: '0'
  Scalar::Util: '0'
  Sub::Identify: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SUPER
  repository: https://github.com/chromatic/SUPER.git
version: '1.20141116'
