---
name: SUPER
version: 1.10
author:
  - Created by Simon Cozens, C<simon@cpan.org>.
abstract: Control superclass method dispatch
license: perl
requires:
  Scalar::Util: ''
build_requires:
  Test::More: ''
provides:
  DB:
    file: lib/SUPER.pm
    version: 1.10
  SUPER:
    file: lib/SUPER.pm
    version: 1.10
  UNIVERSAL:
    file: lib/SUPER.pm
    version: 1.10
generated_by: Module::Build version 0.2608
