---
name: SUPER
version: 1.17
author:
  - 'Created by Simon Cozens, C<simon@cpan.org>.  Copyright (c) 2003 Simon Cozens.'
abstract: control superclass method dispatch
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0.61
requires:
  Scalar::Util: 1.20
  Sub::Identify: 0.03
  perl: v5.6.2
configure_requires:
  Module::Build: 0.35
provides:
  DB:
    file: lib/SUPER.pm
  SUPER:
    file: lib/SUPER.pm
    version: 1.17
  UNIVERSAL:
    file: lib/SUPER.pm
no_index:
  package:
    - UNIVERSAL
    - DB
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
